import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { marked } from 'marked';
import mermaid from 'mermaid';
import DOMPurify from 'dompurify';
import { ShieldAlert, Zap } from 'lucide-react';
import { api, ApiError, getToken, type AnalysisResult } from '@/lib/api';
import { AsciiArt } from '@/components/AsciiArt';

mermaid.initialize({ startOnLoad: false, theme: 'dark', securityLevel: 'strict' });

/** Explanation/plan markdown is generated by an LLM from analyzing arbitrary
 * (possibly attacker-controlled, e.g. public GitHub repos) source code — a
 * crafted README or code comment could make the model emit raw HTML/script.
 * Always sanitize before dangerouslySetInnerHTML. */
function renderMarkdown(md: string): string {
  return DOMPurify.sanitize(marked.parse(md || '') as string);
}

const STATUS_BADGE: Record<string, string> = {
  done: 'border-emerald-900 bg-emerald-950/60 text-emerald-400',
  processing: 'border-blue-900 bg-blue-950/60 text-blue-400',
  pending: 'border-yellow-900 bg-yellow-950/60 text-yellow-400',
  error: 'border-red-900 bg-red-950/60 text-red-400',
};

const RISK_BADGE: Record<string, string> = {
  Critical: 'border-red-900 bg-red-950/60 text-red-400',
  High: 'border-orange-900 bg-orange-950/60 text-orange-400',
  Medium: 'border-yellow-900 bg-yellow-950/60 text-yellow-400',
  Low: 'border-emerald-900 bg-emerald-950/60 text-emerald-400',
};

const SEV_BORDER: Record<string, string> = {
  critical: 'border-red-900 bg-red-950/30',
  high: 'border-orange-900 bg-orange-950/30',
  medium: 'border-yellow-900 bg-yellow-950/30',
  low: 'border-neutral-800 bg-white/5',
};

// The backend runs five agents and reports a completed-stage count (0–5).
const PIPELINE_STAGE_COUNT = 5;

// Flavor text cycled while the pipeline runs — one line per beat of the
// five-agent pipeline (difficulty, explainer, planner, diagram, security),
// written with enough personality that a minute-long wait doesn't feel dead.
const ANALYSIS_FLAVOR_TEXT = [
  'Reading every file like it owes us money.',
  'Sizing up the difficulty like a judge scoring a routine.',
  'Explaining it the way Einstein would — simply, but not simpler.',
  'Sketching the architecture before the ink dries.',
  'Interrogating dependencies one by one.',
  'Running a SWAT sweep for security holes.',
  'Hunting bugs like a bloodhound on a trail.',
  'Cross-examining the code for hidden vulnerabilities.',
  'Turning spaghetti into a straight line.',
  'Mapping how the pieces actually talk to each other.',
  'Drafting the plan a new hire would wish they had.',
  'Double-checking the scary-looking parts twice.',
];

function AnalysisFlavorLine() {
  const [index, setIndex] = useState(0);

  useEffect(() => {
    const id = setInterval(() => {
      setIndex((i) => (i + 1) % ANALYSIS_FLAVOR_TEXT.length);
    }, 2600);
    return () => clearInterval(id);
  }, []);

  return (
    <p
      key={index}
      className="mt-4 animate-[fade-in_0.4s_ease-out] font-mono text-sm text-neutral-400"
    >
      {ANALYSIS_FLAVOR_TEXT[index]}
    </p>
  );
}

type TabName = 'explanation' | 'plan' | 'diagram' | 'security';

function DiagramView({ code }: { code: string }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setFailed(false);

    mermaid
      .render(`diagram-${Date.now()}`, code)
      .then(({ svg }) => {
        if (!cancelled && containerRef.current) {
          containerRef.current.innerHTML = svg;
        }
      })
      .catch(() => {
        if (!cancelled) setFailed(true);
      });

    return () => {
      cancelled = true;
    };
  }, [code]);

  if (failed) {
    return (
      <pre className="mt-4 overflow-x-auto rounded-lg border border-neutral-800 bg-black/40 p-4 font-mono text-xs text-neutral-400">
        {code}
      </pre>
    );
  }

  return <div ref={containerRef} className="overflow-x-auto" />;
}

export function ResultPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [data, setData] = useState<AnalysisResult | null>(null);
  const [activeTab, setActiveTab] = useState<TabName>('explanation');
  const [loadError, setLoadError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) {
      navigate('/');
      return;
    }
    if (!getToken()) {
      navigate('/login');
      return;
    }

    let cancelled = false;
    let attempts = 0;

    async function poll() {
      while (!cancelled) {
        try {
          const result = await api.getAnalysis(id!);
          if (cancelled) return;
          setData(result);

          if (result.status === 'done' || result.status === 'error') return;
        } catch (err) {
          if (!cancelled) {
            setLoadError(
              err instanceof ApiError ? err.message : 'Could not load this analysis.'
            );
          }
          return;
        }

        attempts++;
        await new Promise((r) => setTimeout(r, attempts === 1 ? 2000 : 4000));
      }
    }

    poll();
    return () => {
      cancelled = true;
    };
  }, [id, navigate]);

  const isPolling = data && data.status !== 'done' && data.status !== 'error';
  const isDone = data?.status === 'done';
  const isError = data?.status === 'error';

  if (loadError) {
    return (
      <div className="min-h-screen bg-neutral-950 p-6">
        <div className="mx-auto max-w-3xl">
          <button
            onClick={() => navigate('/dashboard')}
            className="mb-6 block cursor-pointer font-mono text-sm text-neutral-500 transition hover:text-neutral-300"
          >
            ← My Analyses
          </button>
          <div className="rounded-2xl border border-red-900 bg-red-950/40 p-6">
            <p className="mb-1 font-mono font-semibold text-red-400">Couldn't load this analysis</p>
            <p className="text-sm text-red-300/80">{loadError}</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-neutral-950 p-6">
      <div className="mx-auto max-w-3xl">
        <div className="mb-6 flex items-center justify-between">
          <div>
            <button
              onClick={() => navigate('/dashboard')}
              className="mb-1 block cursor-pointer font-mono text-sm text-neutral-500 transition hover:text-neutral-300"
            >
              ← My Analyses
            </button>
            <h1 className="font-mono text-2xl font-bold tracking-tight text-white">
              &gt; {data?.source_type === 'github' ? 'GitHub Analysis' : 'Local Analysis'}
            </h1>
          </div>
        </div>

        {data && (
          <div className="mb-6 rounded-2xl border border-neutral-800 bg-white/5 p-5 backdrop-blur">
            <div className="flex flex-wrap items-center gap-2">
              <span
                className={`rounded-full border px-3 py-1 font-mono text-xs font-medium ${
                  STATUS_BADGE[data.status] || 'border-neutral-800 bg-white/5 text-neutral-400'
                }`}
              >
                {data.status}
              </span>
              {data.difficulty && (
                <span className="rounded-full border border-neutral-700 bg-white/5 px-3 py-1 font-mono text-xs font-medium text-neutral-300">
                  {data.difficulty}
                </span>
              )}
              {data.primary_language && (
                <span className="rounded-full border border-neutral-700 bg-white/5 px-3 py-1 font-mono text-xs font-medium text-neutral-300">
                  {data.primary_language}
                </span>
              )}
              {data.security && (
                <span
                  className={`flex items-center gap-1.5 rounded-full border px-3 py-1 font-mono text-xs font-medium ${
                    RISK_BADGE[data.security.risk_level] ||
                    'border-neutral-800 bg-white/5 text-neutral-400'
                  }`}
                >
                  <ShieldAlert className="h-3 w-3" /> {data.security.risk_level} Risk
                </span>
              )}
              {data.served_from_cache && (
                <span className="flex items-center gap-1.5 rounded-full border border-amber-900 bg-amber-950/60 px-3 py-1 font-mono text-xs font-medium text-amber-400">
                  <Zap className="h-3 w-3" /> Cached
                </span>
              )}
            </div>
            <p className="mt-3 truncate font-mono text-sm text-neutral-500">
              {data.directory_path}
            </p>
            {data.difficulty_reason && (
              <p className="mt-1 text-sm text-neutral-400">{data.difficulty_reason}</p>
            )}
            {data.frameworks && data.frameworks.length > 0 && (
              <div className="mt-3 flex flex-wrap gap-2">
                {data.frameworks.map((f) => (
                  <span
                    key={f}
                    className="rounded-full border border-neutral-800 bg-black/40 px-2.5 py-1 font-mono text-xs text-neutral-400"
                  >
                    {f}
                  </span>
                ))}
              </div>
            )}
          </div>
        )}

        {isPolling && (
          <div className="relative overflow-hidden rounded-2xl border border-neutral-800 bg-white/5 p-10 text-center backdrop-blur">
            <AsciiArt className="pointer-events-none absolute inset-0 h-full w-full opacity-10 mix-blend-screen" />
            <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-neutral-950/40 via-transparent to-neutral-950/60" />
            <div className="relative">
              <div className="mx-auto mb-4 h-8 w-8 animate-spin rounded-full border-4 border-neutral-800 border-t-white" />
              <p className="font-mono font-medium text-neutral-300">Analysing your codebase…</p>
              <p className="mt-1 text-sm text-neutral-500">
                {Math.min(data?.progress ?? 0, PIPELINE_STAGE_COUNT)} of {PIPELINE_STAGE_COUNT} agents
                complete · usually a minute or two
              </p>
              <div className="mx-auto mt-5 h-1.5 w-full max-w-xs overflow-hidden rounded-full bg-neutral-800">
                <div
                  className="h-full rounded-full bg-white transition-all duration-500 ease-out"
                  style={{
                    width: `${(Math.min(data?.progress ?? 0, PIPELINE_STAGE_COUNT) / PIPELINE_STAGE_COUNT) * 100}%`,
                  }}
                />
              </div>
              <AnalysisFlavorLine />
            </div>
          </div>
        )}

        {isError && (
          <div className="rounded-2xl border border-red-900 bg-red-950/40 p-6">
            <p className="mb-1 font-mono font-semibold text-red-400">Analysis failed</p>
            <p className="text-sm text-red-300/80">{data?.error_message || 'Unknown error'}</p>
          </div>
        )}

        {isDone && data && (
          <div>
            <div className="mb-4 flex flex-wrap gap-2">
              {(['explanation', 'plan', 'diagram', 'security'] as TabName[])
                .filter((t) => t !== 'diagram' || data.diagram)
                .filter((t) => t !== 'security' || data.security)
                .map((tab) => (
                  <button
                    key={tab}
                    onClick={() => setActiveTab(tab)}
                    className={`cursor-pointer rounded-lg px-4 py-2 font-mono text-sm font-medium transition ${
                      activeTab === tab
                        ? 'bg-white text-black'
                        : 'bg-white/5 text-neutral-400 hover:bg-white/10 hover:text-neutral-200'
                    }`}
                  >
                    {tab === 'security'
                      ? 'Security'
                      : tab.charAt(0).toUpperCase() + tab.slice(1)}
                  </button>
                ))}
            </div>

            {activeTab === 'explanation' && (
              <div
                className="prose prose-invert max-w-none rounded-2xl border border-neutral-800 bg-white/5 p-7 backdrop-blur"
                dangerouslySetInnerHTML={{ __html: renderMarkdown(data.explanation || '') }}
              />
            )}

            {activeTab === 'plan' && (
              <div
                className="prose prose-invert max-w-none rounded-2xl border border-neutral-800 bg-white/5 p-7 backdrop-blur"
                dangerouslySetInnerHTML={{ __html: renderMarkdown(data.plan || '') }}
              />
            )}

            {activeTab === 'diagram' && data.diagram && (
              <div className="rounded-2xl border border-neutral-800 bg-white/5 p-7 backdrop-blur">
                <DiagramView code={data.diagram} />
              </div>
            )}

            {activeTab === 'security' && data.security && (
              <div className="rounded-2xl border border-neutral-800 bg-white/5 p-7 backdrop-blur">
                <p className="mb-5 text-neutral-300">{data.security.summary}</p>
                {data.security.findings.length === 0 ? (
                  <p className="font-mono font-medium text-emerald-400">
                    No critical security issues detected.
                  </p>
                ) : (
                  <div className="space-y-3">
                    {data.security.findings.map((f, i) => (
                      <div
                        key={i}
                        className={`rounded-r-lg border-l-4 p-4 ${
                          SEV_BORDER[f.severity] || 'border-neutral-800 bg-white/5'
                        }`}
                      >
                        <div className="mb-1 flex items-start justify-between gap-3">
                          <span className="font-mono text-xs font-semibold uppercase text-neutral-400">
                            {f.severity} · {f.category}
                          </span>
                          <span className="font-mono text-xs text-neutral-500">{f.file}</span>
                        </div>
                        <p className="mb-1 text-sm font-medium text-neutral-200">{f.issue}</p>
                        <p className="text-sm text-neutral-400">
                          <span className="font-semibold text-neutral-300">Fix:</span> {f.fix}
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
