import { Link } from 'react-router-dom';

function slugify(heading: string): string {
  return heading
    .replace(/^\d+\.\s*/, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const SECTIONS = [
  {
    heading: '1. Acceptance of these terms',
    paragraphs: [
      'These Terms of Service (the “Terms”) govern your access to and use of Codebase Explainer (the “service”). By creating an account or using the service, you agree to these Terms. If you do not agree, do not use the service.',
      'If you use the service on behalf of an organization, you represent that you have authority to bind that organization to these Terms, and “you” refers to that organization.',
    ],
  },
  {
    heading: '2. The service',
    paragraphs: [
      'Codebase Explainer analyzes source code you submit — a local directory on the machine running the service, or a public GitHub repository — and returns AI-generated output: a difficulty assessment, a plain-language explanation, a phased plan, an architecture diagram, and a security audit.',
      'The output is generated by large-language-model inference and is provided for informational purposes only. It may contain errors or omissions and is not a substitute for professional review. In particular, the security audit is a best-effort automated scan, not a guarantee that your code is free of vulnerabilities.',
    ],
  },
  {
    heading: '3. Your account',
    paragraphs: [
      'You are responsible for safeguarding your account credentials and for all activity under your account. Provide accurate registration information and keep it current. Notify us promptly of any unauthorized use.',
      'You must be old enough to form a binding contract in your jurisdiction to use the service. The service is not directed to children under 13.',
    ],
  },
  {
    heading: '4. Acceptable use',
    paragraphs: [
      'You agree not to: submit code or content you do not have the right to submit; use the service to violate any law or infringe anyone’s rights; attempt to disrupt, overload, reverse-engineer, or circumvent the security or rate limits of the service; or resell or redistribute the service without our permission.',
      'We may enforce usage quotas and rate limits, and we may suspend or terminate accounts that abuse the service or place it at risk.',
    ],
  },
  {
    heading: '5. Your code and content',
    paragraphs: [
      'You retain all rights to the code and content you submit. You grant us a limited license to process it solely to provide the service — ingesting it, transmitting selected snippets to our large-language-model inference provider, and generating and storing the resulting analysis. See the Privacy Policy for full details of what is stored and what is not.',
      'You are responsible for what you submit. We recommend not submitting codebases that contain production secrets; the safest secret is one that never leaves your machine.',
    ],
  },
  {
    heading: '6. Intellectual property',
    paragraphs: [
      'The service, including its software, design, and branding, is owned by us and protected by intellectual-property laws. These Terms do not grant you any right to our trademarks or branding. The analysis output generated for you is yours to use, subject to these Terms and the rights of any third parties whose code you submitted.',
    ],
  },
  {
    heading: '7. Third-party services',
    paragraphs: [
      'The service relies on third parties, including a large-language-model inference provider and, when you analyze a public repository, GitHub. Your use of the service in connection with those providers is also subject to their terms. We are not responsible for third-party services.',
    ],
  },
  {
    heading: '8. Disclaimers',
    paragraphs: [
      'The service is provided “as is” and “as available,” without warranties of any kind, whether express or implied, including warranties of merchantability, fitness for a particular purpose, non-infringement, and any warranty as to the accuracy, completeness, or reliability of the analysis output. You use the output at your own discretion and risk.',
    ],
  },
  {
    heading: '9. Limitation of liability',
    paragraphs: [
      'To the maximum extent permitted by law, we will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of data, profits, or goodwill, arising from or related to your use of the service. Our total liability for any claim relating to the service will not exceed the greater of the amount you paid us for the service in the twelve months before the claim, or USD 100.',
    ],
  },
  {
    heading: '10. Termination',
    paragraphs: [
      'You may stop using the service and request deletion of your account at any time. We may suspend or terminate your access if you violate these Terms or if we discontinue the service. Provisions that by their nature should survive termination — including ownership, disclaimers, and limitation of liability — will survive.',
    ],
  },
  {
    heading: '11. Changes to these terms',
    paragraphs: [
      'We may update these Terms as the service evolves. Material changes will be announced on this page with an updated effective date, and where appropriate, by email. Continued use of the service after changes take effect constitutes acceptance of the revised Terms.',
    ],
  },
  {
    heading: '12. Contact',
    paragraphs: [
      'Questions about these Terms can be sent to legal@codebase-explainer.app.',
    ],
  },
];

export function TermsPage() {
  return (
    <div className="min-h-screen bg-neutral-950 px-6 py-16">
      <div className="mx-auto max-w-2xl">
        <Link
          to="/"
          className="mb-8 block font-mono text-sm text-neutral-500 transition hover:text-neutral-300"
        >
          ← Back
        </Link>

        <h1 className="font-mono text-3xl font-bold tracking-tight text-white">
          &gt; Terms of Service
        </h1>
        <p className="mt-2 font-mono text-xs text-neutral-500">Effective date: July 6, 2026</p>

        <div className="mt-5 rounded-xl border border-neutral-800 bg-white/5 p-5">
          <p className="mb-1 font-mono text-xs font-semibold uppercase tracking-wide text-neutral-500">
            TL;DR
          </p>
          <p className="text-sm leading-relaxed text-neutral-300">
            Use Codebase Explainer responsibly and only on code you have the right to submit.
            The AI-generated analysis is best-effort and provided “as is” — review it before
            relying on it. You keep the rights to your code; we only process it to run the
            service you asked for.
          </p>
        </div>

        <nav aria-label="Table of contents" className="mt-8 rounded-xl border border-neutral-800 p-5">
          <p className="mb-3 font-mono text-xs font-semibold uppercase tracking-wide text-neutral-500">
            On this page
          </p>
          <ol className="grid grid-cols-1 gap-x-6 gap-y-1.5 sm:grid-cols-2">
            {SECTIONS.map((s) => (
              <li key={s.heading}>
                <a
                  href={`#${slugify(s.heading)}`}
                  className="text-sm text-neutral-400 transition hover:text-white hover:underline"
                >
                  {s.heading}
                </a>
              </li>
            ))}
          </ol>
        </nav>

        <div className="mt-10 space-y-8">
          {SECTIONS.map((s) => (
            <section key={s.heading} id={slugify(s.heading)} className="scroll-mt-8">
              <h2 className="mb-3 font-mono text-sm font-semibold text-white">{s.heading}</h2>
              <div className="space-y-3">
                {s.paragraphs.map((p, i) => (
                  <p key={i} className="text-sm leading-relaxed text-neutral-400">
                    {p}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>

        <p className="mt-10 border-t border-neutral-900 pt-6 text-center text-xs text-neutral-600">
          See also our{' '}
          <Link to="/privacy" className="underline transition hover:text-neutral-400">
            Privacy Policy
          </Link>
          .
        </p>
      </div>
    </div>
  );
}
